[buildpack]
  id = "qutheory.buildpacks.vapor"
  version = "0.0.1"
  name = "Vapor"

[[stacks]]
id = "heroku-18"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"